#!/bin/sh

logger -t DEBUG "hotplug (iface): action='$ACTION' interface='$INTERFACE'"

local _wwan _wait

 _wwan=wwan
_wait=15

if [ "$ACTION" = ifdown -a "$INTERFACE" = "$_wwan" ]; then
	ENB=$(uci get wireless.wwan.disabled)
	if [ $ENB -eq 1 ]; then
		/usr/sbin/revert_to_AP.sh $_wait $_wwan
	fi
fi