#!/bin/sh

ROOTER=/usr/lib/rooter

log() {
	logger -t "sms process" "$@"
}

log "SMS Supported"

CURRMODEM=$1
COMMPORT="/dev/ttyUSB"$(uci get modem.modem$CURRMODEM.commport)

LOCKDIR="/tmp/smslock$CURRMODEM"
PIDFILE="${LOCKDIR}/PID"
rm -rf "${LOCKDIR}"

ATCMDD="AT+CMGF=0"
OX=$($ROOTER/gcom/gcom-locked "$COMMPORT" "run-at.gcom" "$CURRMODEM" "$ATCMDD")
uci set modem.modem$CURRMODEM.smsnum=999
uci commit modem
ATCMDD="AT+CPMS=\"ME\""
OX=$($ROOTER/gcom/gcom-locked "$COMMPORT" "run-at.gcom" "$CURRMODEM" "$ATCMDD")
MEC=$(echo "$OX" | grep -o "+CPMS:.*" | awk -F, '{print $1}' | grep -o "[0-9]\{1,3\}")
if [ "x$MEC" = "x" ]; then
	MEC="0"
fi
if [ $MEC -gt 0 ];then
	log "SMS ME storage contains $MEC messages"
fi
sleep 5
ATCMDD="AT+CPMS=\"SM\""
OX=$($ROOTER/gcom/gcom-locked "$COMMPORT" "run-at.gcom" "$CURRMODEM" "$ATCMDD")
sleep 5

rm -f /tmp/smsresult$CURRMODEM".at"

while [ 1 -lt 6 ]; do
	while [ 1 -lt 6 ]; do
		if mkdir "${LOCKDIR}" &>/dev/null; then
			echo "$$" > "${PIDFILE}"
			ATCMDD="AT+CPMS=\"SM\""
			SX=$($ROOTER/gcom/gcom-locked "$COMMPORT" "run-at.gcom" "$CURRMODEM" "$ATCMDD")
			M2=$(echo "$SX" | sed -e "s/+CPMS:/+CPMS: /")
			SX=$(echo "$M2" | sed -e "s/  / /g")
			USED=$(echo "$SX" | awk -F[,\ ] '/^\+CPMS:/ {print $2}')
			MAXED=$(echo "$SX" | awk -F[,\ ] '/^\+CPMS:/ {print $3}')
			NUMB=$(uci get modem.modem$CURRMODEM.smsnum)
			if [ $USED != $NUMB ]; then
				log "Reread SMS Messages on Modem $CURRMODEM"
				echo "$SX" > /tmp/smstemp$CURRMODEM
				ATCMDD="AT+CMGL=4"
				SX=$($ROOTER/gcom/gcom-locked "$COMMPORT" "run-at.gcom" "$CURRMODEM" "$ATCMDD")
				SX=$(echo "$SX" | sed -e "s/+CMGL:/+CMGL: /g")
				echo "$SX" >> /tmp/smstemp$CURRMODEM
				uci set modem.modem$CURRMODEM.smsnum=$USED
				uci commit modem
				mv /tmp/smstemp$CURRMODEM /tmp/smsresult$CURRMODEM.at
			fi
			break
		else
			OTHERPID="$(cat "${PIDFILE}")"
			if [ $? = 0 ]; then
				if ! kill -0 $OTHERPID &>/dev/null; then
 					rm -rf "${LOCKDIR}"
				fi
			fi
			sleep 1
		fi
	done
	rm -rf "${LOCKDIR}"
	sleep 20
done
